"""
Documentation download utility for TeleBot Studio MCP.

Reads URLs from urls.txt (generated by crawler.py), downloads each page,
converts the HTML to Markdown, and saves the result in the docs/ directory.

Usage:
    python download_docs.py                  # Download all URLs from urls.txt
    python download_docs.py urls.txt docs/   # Custom input/output paths

Prerequisites:
    pip install requests beautifulsoup4 lxml markdownify
"""

from __future__ import annotations

import logging
import os
import sys
from urllib.parse import urlparse

import requests
from bs4 import BeautifulSoup
from markdownify import markdownify

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
)
logger = logging.getLogger("download_docs")

DEFAULT_URLS_FILE = "urls.txt"
DEFAULT_DOCS_DIR = "docs"
DEFAULT_TIMEOUT = 30

# HTML tags to remove before converting to Markdown
REMOVE_TAGS = ["script", "style", "noscript", "footer", "header", "nav"]


def download_docs(
    urls_file: str = DEFAULT_URLS_FILE,
    docs_dir: str = DEFAULT_DOCS_DIR,
    timeout: int = DEFAULT_TIMEOUT,
) -> tuple[int, int]:
    """
    Download documentation pages and convert them to Markdown.

    Args:
        urls_file: Path to the file containing URLs (one per line).
        docs_dir: Directory to save the converted Markdown files.
        timeout: HTTP request timeout in seconds.

    Returns:
        Tuple of (successful_downloads, total_urls).
    """
    if not os.path.exists(urls_file):
        logger.error("URLs file not found: %s", urls_file)
        logger.info("Run crawler.py first to generate the URL list.")
        return 0, 0

    os.makedirs(docs_dir, exist_ok=True)

    with open(urls_file, encoding="utf-8") as f:
        urls = [line.strip() for line in f if line.strip()]

    if not urls:
        logger.error("No URLs found in %s", urls_file)
        return 0, 0

    logger.info("Downloading %d pages to %s/", len(urls), docs_dir)

    success_count = 0

    for i, url in enumerate(urls, start=1):
        # Skip email protection links
        if "/l/email-protection" in url:
            logger.debug("  Skipping email protection link: %s", url)
            continue

        try:
            logger.info("  [%d/%d] Downloading: %s", i, len(urls), url)

            response = requests.get(url, timeout=timeout)
            if response.status_code != 200:
                logger.warning("  Status %d for %s", response.status_code, url)
                continue

            soup = BeautifulSoup(response.text, "lxml")

            # Remove unnecessary elements
            for tag in soup(REMOVE_TAGS):
                tag.decompose()

            # Convert to Markdown
            md_content = markdownify(str(soup), heading_style="ATX")

            # Generate filename from URL
            name = _url_to_filename(url)

            # Save the file
            output_path = os.path.join(docs_dir, name)
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(md_content)

            success_count += 1
            logger.debug("  Saved: %s", output_path)

        except requests.Timeout:
            logger.warning("  Timeout: %s", url)
        except requests.ConnectionError:
            logger.warning("  Connection error: %s", url)
        except Exception as e:
            logger.error("  Error downloading %s: %s", url, e)

    logger.info(
        "Download complete: %d/%d pages saved to %s/",
        success_count,
        len(urls),
        docs_dir,
    )

    return success_count, len(urls)


def _url_to_filename(url: str) -> str:
    """Convert a URL to a Markdown filename."""
    parsed = urlparse(url)
    path = parsed.path.rstrip("/")
    name = path.split("/")[-1] if path else "index"

    if not name:
        name = "index"

    if not name.endswith(".md"):
        name += ".md"

    # Sanitize the filename
    name = "".join(c if c.isalnum() or c in "-_." else "_" for c in name)

    return name


def main() -> None:
    urls_file = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_URLS_FILE
    docs_dir = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_DOCS_DIR

    download_docs(urls_file, docs_dir)


if __name__ == "__main__":
    main()
